/// Commemoration display names (saints & feasts), ported from the MIT-licensed
/// orthocal-python fixture (`fixtures/calendarium.json`). Generated by
/// tool/gen_commemorations.dart — do not hand-edit.
///
/// Content data, English only for v1 (names are facts, no copyright — see
/// CLAUDE.md). Names per day are ordered principal-feast first. The engine's
/// titleKey still names the season/movable feast; these add the saints.
///
/// FLUTTER IMPORT FORBIDDEN (architecture principle #2).
library;

/// Fixed-date (menaion) commemoration names, keyed by `month * 100 + day`.
const Map<int, List<String>> fixedCommemorationNames = {
  101: ['Circumcision of Our Lord; St Basil the Great'], // 01-01
  102: ['Forefeast of Theophany', 'Repose of St Seraphim of Sarov'], // 01-02
  103: ['Forefeast of Theophany', 'Prophet Malachi'], // 01-03
  104: ['Forefeast of Theophany', 'Synaxis of Seventy Apostles'], // 01-04
  106: ['Theophany of Our Lord and Savior Jesus Christ'], // 01-06
  107: ['Synaxis of St John the Baptist'], // 01-07
  108: ['Ven. George the Chozebite'], // 01-08
  109: [
    'Martyr Polyeuctus of Melitene in Armenia',
    'Hieromartyr Philip, Metropolitan of Moscow'
  ], // 01-09
  110: ['St Gregory of Nyssa', 'St Theophan the Recluse'], // 01-10
  111: ['Ven. Theodosius the Great'], // 01-11
  112: ['St Sava, Archbishop of Serbia'], // 01-12
  113: ['Martyrs Hermylus and Stratonicus'], // 01-13
  114: ['Leavetaking of Theophany', 'St Nino of Georgia'], // 01-14
  115: ['Ven. Paul of Thebes and John Calabytes'], // 01-15
  116: ['Veneration of Chains of Apostle Peter'], // 01-16
  117: ['Ven. Godbearing Anthony the Great'], // 01-17
  118: ['Ss Athanasius the Great and Cyril of Alexandria'], // 01-18
  119: ['Ven. Macarius the Great'], // 01-19
  120: ['Ven. Euthymius the Great'], // 01-20
  121: ['Ven. Maximus the Confessor'], // 01-21
  122: ['Apostle Timothy of the Seventy'], // 01-22
  123: ['Hieromartyr Clement and Martyr Agathangel'], // 01-23
  124: ['Ven. Xenia of Rome', 'Bl. Xenia of St Petersburg'], // 01-24
  125: ['St Gregory the Theologian'], // 01-25
  126: ['Ven. Xenophon and Mary'], // 01-26
  127: ['Transl. Relics of St John Chrysostom'], // 01-27
  128: ['Ven. Ephrem the Syrian'], // 01-28
  129: ['Trans. Rel. Ignatius the Godbearer'], // 01-29
  130: [
    'Synaxis 3 Hierarchs: Basil the Great, Gregory the Theologian, John Chrysostom'
  ], // 01-30
  131: ['Unmercenaries Cyrus and John'], // 01-31
  201: ['Martyr Tryphon'], // 02-01
  202: ['Meeting of Christ in the Temple'], // 02-02
  203: ['Righteous Simeon the Godbearer and Anna the Prophetess'], // 02-03
  204: ['Ven. Isidore of Pelusium'], // 02-04
  205: ['Repose St Theodosius of Chernigov'], // 02-05
  206: ['St Bucolus, Bishop of Smyrna'], // 02-06
  207: ['St Parthenius, Bishop of Lampsacus'], // 02-07
  208: ['Greatmartyr Theodore Stratelates'], // 02-08
  209: [
    'Leavetaking of Meeting',
    'Martyr Nicephorus of Antioch',
    'Relics of St Innocent of Irkutsk'
  ], // 02-09
  210: ['Hieromartyr Haralambos'], // 02-10
  211: ['Hieromartyr Blaise of Sebaste', 'Ven. Dimitry of Priluk'], // 02-11
  212: [
    'St Meletius, Archbishop of Antioch',
    'St Aleksy, Metr. of All Russia'
  ], // 02-12
  213: ['Ven. Martinian of Caesarea'], // 02-13
  214: ['St Cyril, Teacher of the Slavs'], // 02-14
  215: ['Apostle Onesimus of the Seventy'], // 02-15
  216: ['Martyr Pamphylius and His Companions'], // 02-16
  217: [
    'Greatmartyr Theodore Tyro',
    'Hieromartyr Germogen, Patriarch of Moscow'
  ], // 02-17
  218: ['St Leo the Great, Pope of Rome'], // 02-18
  219: ['Apostles of the Seventy Archippus and Philemon'], // 02-19
  220: ['St Leo, Bishop of Catania'], // 02-20
  221: ['Ven. Timothy of Symbola'], // 02-21
  222: ['Unc. Rel. Holy Martyrs at Gate of Eugenius'], // 02-22
  223: ['Hieromartyr Polycarp, Bishop of Smyrna'], // 02-23
  224: ['1st and 2nd Finding Honorable Head of St John the Baptist'], // 02-24
  225: ['St Tarasius, Abp. of Constantinople'], // 02-25
  226: ['St Porphyrius, Bishop of Gaza'], // 02-26
  227: ['St Raphael Bishop of Brooklyn'], // 02-27
  228: ['Ven. Basil the Confessor'], // 02-28
  229: ['Ven. John Cassian'], // 02-29
  301: ['Martyr Eudoxia of Heliopolis'], // 03-01
  302: [
    'Hieromartyr Theodotus, Bishop of Cyrenia',
    'St Arseny, Bishop of Tver'
  ], // 03-02
  303: ['Martyrs Eutropius, Cleonicus and Basiliscus'], // 03-03
  304: [
    'Ven. Gerasimus of the Jordan',
    'Rt. Blv. Prince Daniel of Moscow'
  ], // 03-04
  305: ['Martyr Conon of Isauria'], // 03-05
  306: ['Forty-two Martyrs of Ammoria'], // 03-06
  307: ['Seven Hieromartyrs of Cherson'], // 03-07
  308: ['St Theophylactus, Bishop of Nicomedia'], // 03-08
  309: ['Holy Forty Martyrs of Sebaste'], // 03-09
  310: ['Martyr Quadratus and Companions'], // 03-10
  311: [
    'St. Sophronius, Patriarch of Jerusalem',
    'St Euthymius, Bishop of Novgorod'
  ], // 03-11
  312: ['Ven. Theophanes the Confessor'], // 03-12
  313: ['Trans. Rel. Nicephorus, Patr. Constantinopole'], // 03-13
  314: ['Ven. Benedict of Nursia'], // 03-14
  315: ['Martyr Agapius and Seven with Him'], // 03-15
  316: ['Martyr Sabinas of Egypt'], // 03-16
  317: ['Ven. Alexius the Man of God', 'Ven. Makary of Kalyazinsk'], // 03-17
  318: [
    'St Cyril, Archbishop of Jerusalem',
    'Rep. St Nikolaj of Zhicha'
  ], // 03-18
  319: ['Martyrs Chrysanthius and Daria'], // 03-19
  320: ['Holy Fathers Slain at St Sabbas Monastery'], // 03-20
  321: ['St James the Confessor of Catania'], // 03-21
  322: ['Hieromartyr Basil of Ancyra'], // 03-22
  323: ['Martyr Nikon and 199 Disciples'], // 03-23
  324: ['Forefeast of Annunciation', 'Ven. Zachariah the Recluse'], // 03-24
  325: ['Annunciation Most Holy Theotokos'], // 03-25
  326: ['Leavetaking of Annunciation', 'Synaxis of Archangel Gabriel'], // 03-26
  327: ['Martyr Matrona of Thessalonica'], // 03-27
  328: ['Ven. Hilarion the New'], // 03-28
  329: ['Hieromartyr Mark, Bishop of Anthusa'], // 03-29
  330: ['Ven. John Climacus'], // 03-30
  331: ['Repose St Innocent, Metr. Moscow and Apostle to Americas'], // 03-31
  401: ['Ven. Euthymius of Suzdal'], // 04-01
  402: ['Ven. Titus the Wonderworker'], // 04-02
  403: ['Ven. Nicetas the Confessor'], // 04-03
  404: ['Ven. Joseph the Hymnographer'], // 04-04
  405: ['Martyrs Agathopedes, Theodulus and Their Companions'], // 04-05
  406: ['St Methodius, Enilightener of the Slavs'], // 04-06
  407: [
    'Repose St. Tikhon, Patriarch of Moscow, Enlightener N. America'
  ], // 04-07
  408: [
    'Apostles of the Seventy Herodion, Agabus, Asyncritus, Rufuf, Phlegon, Hermes'
  ], // 04-08
  409: ['Martyr Eupsychius of Caesarea in Cappadocia'], // 04-09
  410: ['Martyrs Terence, Pompeius, Africanus and Companions'], // 04-10
  411: ['Hieromartyr Antipas, Bishop of Pergamum'], // 04-11
  412: ['St Basil the Confessor, Bishop of Parium'], // 04-12
  413: ['Hieromartyr Artemon, Presbyter of Laodicea'], // 04-13
  414: ['St Martin the Confessor, Pope of Rome'], // 04-14
  415: ['Apostles of the Seventy Aristarchus, Pudens and Trophimus'], // 04-15
  416: ['Virgin Martyrs Agape, Irene and Chionia'], // 04-16
  417: ['Ven. Zosima of Solovetsk'], // 04-17
  418: ['Ven. John, Disciple of Gregory Decapolites'], // 04-18
  419: ['Ven. John of Ancient Caves in Palestine'], // 04-19
  420: ['Ven. Theodore Trichinas'], // 04-20
  421: ['Hieromartyr Januarius and Companions'], // 04-21
  422: ['St Theodore the Sykeote'], // 04-22
  423: ['Holy Greatmartyr, Victorybearer and Wonderworker George'], // 04-23
  424: ['Martyr Sabbas Stratelates'], // 04-24
  425: ['Holy Apostle and Evangelist Mark'], // 04-25
  426: ['St Stephen, Bishop of Perm'], // 04-26
  427: ['Hieromartyr Simeon, Kinsman of the Lord'], // 04-27
  428: ['Apostles Jason and Sosipater of the Seventy'], // 04-28
  429: ['Nine Martyrs at Cyzicus'], // 04-29
  430: ['Holy Apostle James, Brother of St John'], // 04-30
  501: ['Prophet Jeremiah', 'Ven. Paphnutius of Borovsk'], // 05-01
  502: [
    'Trans. Rel. Boris and Gleb',
    'St Athanasius the Great, Patr. of Alexandria'
  ], // 05-02
  503: ['Ven. Theodosius, Abbot of the Kiev Caves'], // 05-03
  504: ['Virgin Martyr Pelagia of Tarsus'], // 05-04
  505: ['Great Martyr Irene of Thessalonica'], // 05-05
  506: ['Righteous Job the Longsuffering'], // 05-06
  507: [
    'St Alexis Toth, Confessor and Defender of Orthodoxy in America'
  ], // 05-07
  508: ['Holy Apostle John the Theologian'], // 05-08
  509: ['Prophet Isaiah', 'Trans. Rel. St Nicholas the Wonderworker'], // 05-09
  510: ['Apostle Simon the Zealot'], // 05-10
  511: ['SS Cyril and Methodius, Apostles to the Slavs'], // 05-11
  512: ['St Epiphanius, Bishop of Cyprus'], // 05-12
  513: ['Virgin Martyr Glyceria'], // 05-13
  514: ['Ven. Isidore, Fool-for-Christ of Rostov'], // 05-14
  515: [
    'Ven. Pachomius the Great',
    'Slain Crown Prince Dimitry of Moscow'
  ], // 05-15
  516: [
    'Ven. Theodore the Sanctified',
    'Trans. Rel. Ephraim, Abbot of Perekop'
  ], // 05-16
  517: ['Apostle Andronicus of the Seventy'], // 05-17
  518: ['Martyr Theodotus of Ancyra'], // 05-18
  519: ['Hieromartyr Patrick, Bishop of Prusa'], // 05-19
  520: ['Unc. Rel. St Aleksy, Metropolitan of Kiev'], // 05-20
  521: ['SS Constantine and Helen, Equals-to-the-Apostles'], // 05-21
  522: ['Martyr Basiliscus, Bishop of Comana'], // 05-22
  523: [
    'St Michael the Confessor',
    'Unc. Rel. St Leonty, Bishop of Rostov'
  ], // 05-23
  524: ['Ven. Simeon the Stylite', 'Ven. Nikita the Stylite'], // 05-24
  525: ['3rd Finding of the Head of St John the Baptist'], // 05-25
  526: [
    'Apostles Carpus and Alphaeus of the Seventy',
    'Greatmartyr George the New at Sofia'
  ], // 05-26
  527: ['Hieromartyr Therapon', 'Trans. Rel. Ven. Nilus of Stolbensk'], // 05-27
  528: [
    'St Nicetas, Bishop of Chalcedon',
    'St Ignaty, Bishop of Rostov'
  ], // 05-28
  529: ['Virgin Martyr Theodosia of Tyre', 'Rep. Bl. John of Ustiug'], // 05-29
  530: ['Ven. Isaac, Founder of Dalmatian Monastery'], // 05-30
  531: ['Apostle Hermes of the Seventy'], // 05-31
  601: ['Martyr Justin the Philosopher'], // 06-01
  602: ['St Nicephorus the Confessor'], // 06-02
  603: ['Martyr Lucillian and His Companions'], // 06-03
  604: ['St Metrophanes, First Patriarch of Constantinople'], // 06-04
  605: ['Hieromartyr Dorotheus, Bishop of Tyre'], // 06-05
  606: ['Ven. Bessarion the Wonderworker of Egypt'], // 06-06
  607: ['Hieromartyr Theodotus, Bishop of Ancyra'], // 06-07
  608: ['Trans. Rel. Theodore Stratelates'], // 06-08
  609: ['St Cyril of Alexandria', 'Ven. Kirill of Belozersk'], // 06-09
  610: [
    'Hieromartyr Timothy, Bishop of Prusa',
    'St John Maximovitch, Metropolitan of Tobolsk'
  ], // 06-10
  611: ['Holy Apostles Bartholomew and Barnabas'], // 06-11
  612: ['Ven. Onuphrius the Great'], // 06-12
  613: ['Martyr Aquilina of Byblos'], // 06-13
  614: ['Prophet Elisha'], // 06-14
  615: ['Prophet Amos', 'St Jonah, Metr. of Moscow'], // 06-15
  616: ['St Tycho, Bishop of Amathus'], // 06-16
  617: ['Martyrs Manuel, Sabel, Ismael of Persia'], // 06-17
  618: ['Martyr Leontius and Companions'], // 06-18
  619: ['Holy Apostle Jude, Brother of the Lord'], // 06-19
  620: ['Hieromartyr Methodius, Bishop of Patar'], // 06-20
  621: ['Martyr Julian of Tarsus'], // 06-21
  622: ['Hieromartyr Eusebius, Bishop of Samosata'], // 06-22
  623: ['Martyr Agrippina of Rome'], // 06-23
  624: ['Nativity of St John the Baptist'], // 06-24
  625: ['Virgin Martyr Febronia', 'Peter and Fevronia of Murom'], // 06-25
  626: ['Ven. David of Thessalonica', 'Tikhvin Icon'], // 06-26
  627: ['Ven. Sampson the Hospitable of Constantinople'], // 06-27
  628: ['Trans. Rel. Ven. Cyrus and John'], // 06-28
  629: ['Holy Apostles Peter and Paul'], // 06-29
  630: ['Synaxis of the Twelve Apostles'], // 06-30
  701: ['Unmercenary Wonderworkers Cosmas and Damian'], // 07-01
  702: ['Robe of the Theotokos at Blachernae'], // 07-02
  703: ['Martyr Hyacinth', 'Trans. Rel. Philip, Metr. Moscow'], // 07-03
  704: ['St Andrew of Crete'], // 07-04
  705: [
    'Unc. Rel. Ven. Sergius of Radonezh; Ven. Athanasius of Athos'
  ], // 07-05
  706: ['Ven. Sisoes the Great'], // 07-06
  707: ['Ven. Thomas of Mt Maleon'], // 07-07
  708: ['Greatmartyr Procopius of Caesarea'], // 07-08
  709: ['Hieromartyr Pancratius, Bishop of Taormina'], // 07-09
  710: ['Ven. Anthony of the Kiev Caves'], // 07-10
  711: ['Greatmartyr Euphemia', 'Blessed Princess Olga'], // 07-11
  712: ['Martyrs Proclus and Hilary of Ancyra'], // 07-12
  713: ['Synaxis of Archangel Gabriel'], // 07-13
  714: ['Apostle Aquila of the Seventy'], // 07-14
  715: [
    'Great Prince Vladimir, Equal-to-the-Apostles, Enlightener of the Lands of Rus'
  ], // 07-15
  716: ['Hieromartyr Athenogenes, Bishop of Heracleopolis'], // 07-16
  717: ['Royal Passionbearers', 'Greatmartyr Marina'], // 07-17
  718: ['Martyr Emilian of Silistria'], // 07-18
  719: ['Unc. Rel. Ven. Seraphim of Sarov'], // 07-19
  720: ['Holy Prophet Elijah'], // 07-20
  721: ['Prophet Ezekiel'], // 07-21
  722: ['Holy Myrrhbearer Mary Magdalene, Equal-to-the-Apostles'], // 07-22
  723: ['Martys Trophimus, Theophilus and Companions'], // 07-23
  724: ['Martyrs Boris and Gleb, Passionbearers'], // 07-24
  725: ['Dormition Righteous Anna, Mother of Theotokos'], // 07-25
  726: [
    'Repose of St Jacob Netsvetov, Enlightener of the Peoples of Alaska'
  ], // 07-26
  727: ['Greatmartyr and Healer Panteleimon'], // 07-27
  728: ['Apostles of 70 Prochorus, Nicanor, Timon, Parmenas'], // 07-28
  729: ['Martyr Callinicus of Gangra'], // 07-29
  730: ['Apostles Silas and Silvanus of the Seventy'], // 07-30
  731: [
    'Forefeast of the Procession of the Lifegiving Cross',
    'Righteous Joseph of Arimathea'
  ], // 07-31
  801: [
    'Procession of the Lifegiving Cross; 7 Maccabean Martyrs',
    'Begin Dormition Fast'
  ], // 08-01
  802: [
    'Trans. Rel. Protomartyr Stephen',
    'Bl. Vasily, Fool-for-Christ'
  ], // 08-02
  803: [
    'Ven. Isaac, Dalmatius, Faustus',
    'Ven. Anthony the Roman of Novgorod'
  ], // 08-03
  804: ['Seven Sleepers of Ephesus'], // 08-04
  805: ['Martyr Eusignius of Antioch'], // 08-05
  806: ['Transfiguration of Our Lord'], // 08-06
  807: ['Martyr Dometius of Persia'], // 08-07
  808: ['St Emilian the Confessor'], // 08-08
  809: ['Ven. Herman of Alaska, Wonderworker of All America'], // 08-09
  810: ['Holy Martyr and Archdeacon Lawrence of Rome'], // 08-10
  811: ['Holy Martyr and Archdeacon Euplus of Catania'], // 08-11
  812: ['Martyrs Anicletus and Photius of Nicomedia'], // 08-12
  813: ['St Tikhon of Zadonsk'], // 08-13
  814: ['Prophet Micah'], // 08-14
  815: ['Dormition of the Most-Holy Theotokos'], // 08-15
  816: ['Image of Christ Not Made by Hands'], // 08-16
  817: ['Martyr Myron, Presbyter of Cyzicus'], // 08-17
  818: ['Martyrs Florus and Laurus of Illyria'], // 08-18
  819: ['Martyr Andrew Stratelates and Companions'], // 08-19
  820: ['Prophet Samuel'], // 08-20
  821: [
    'Apostle Thaddeus of the Seventy',
    'Avram, Archimandrite of Smolensk'
  ], // 08-21
  822: ['Martyr Agathonicus and Companions'], // 08-22
  823: ['Martyr Lupus, Slave of St Demetrius'], // 08-23
  824: ['Hieromartyr Eutichius', 'Trans. Rel. Peter, Metr. Kiev'], // 08-24
  825: ['Relics of Apostle Bartholomew'], // 08-25
  826: ['Martyrs Adrian and Natalia', 'Vladimir Icon'], // 08-26
  827: ['Ven. Poemen the Great'], // 08-27
  828: ['Ven. Job of Pochaev'], // 08-28
  829: ['Beheading of St John the Baptist'], // 08-29
  830: [
    'Ss Alexander, John, Paul, Pats. Constantinople',
    'Trans. Rel. St Alexander Nevsky'
  ], // 08-30
  831: ['Sash of the Theotokos'], // 08-31
  901: ['Church New Year; Ven. Simeon the Stylite (The Elder)'], // 09-01
  902: ['Ven. Anthony and Theodosius of Kiev Caves'], // 09-02
  903: ['Hieromartyr Anthimus, Bishop of Nicomedia'], // 09-03
  904: ['Hieromartyr Babylas, Bishop of Antioch'], // 09-04
  905: ['Prophet Zachariah'], // 09-05
  906: ['Miracle of Archangel Michael at Colossae'], // 09-06
  907: ['Martyr Sozon of Cilicia', 'St John, Archbishop of Novgorod'], // 09-07
  908: ['Nativity of the Most-Holy Theotokos'], // 09-08
  909: ['Righteous Joachim and Anna', 'Ven. Joseph of Volotsk'], // 09-09
  910: ['Martyrs Menodora, Metrodora, Nymphodora'], // 09-10
  911: ['Ven. Theodora of Alexandria'], // 09-11
  912: ['Hieromartyr Autonomus, Bishop in Italy'], // 09-12
  913: ['Founding of Church of the Holy Sepulchre'], // 09-13
  914: ['Exaltation (Elevation) of the Precious Cross'], // 09-14
  915: ['Greatmartyr Nicetas the Goth'], // 09-15
  916: ['Greatmartyr Euphemia the All-Praised'], // 09-16
  917: ['Martyr Sophia and Daughters Faith, Hope, and Love'], // 09-17
  918: ['St Eumenes, Bishop of Gortyna'], // 09-18
  919: [
    'Martyrs Trophimus, Sabbatius, Dorymedon',
    'Ss David and Constantine of Yaroslavl'
  ], // 09-19
  920: [
    'Greatmartyr Eustathius and Martyr Theopistes',
    'Martyrs Michael and Theodore of Chernigov'
  ], // 09-20
  921: [
    'Apostle Quadratus of the Seventy',
    'Unc. Rel. St Dimitry, Metr. Rostov'
  ], // 09-21
  922: ['Hieromartyr Phocas, Bishop of Sinope'], // 09-22
  923: ['Conception of St John the Baptist'], // 09-23
  924: ['Holy New Martyrs of Alaska'], // 09-24
  925: ['Repose of Ven. Sergius of Radonezh'], // 09-25
  926: ['Repose of St John the Theologian'], // 09-26
  927: [
    'Martyr Callistratus and Companions',
    'Ven. Sabbatius of Solovetsk'
  ], // 09-27
  928: ['Ven. Chariton the Confessor'], // 09-28
  929: ['Ven. Cyriacos, Hermit of Palestine'], // 09-29
  930: ['Hieromartyr Gregory of Armenia', 'Ven. Gregory of Vologda'], // 09-30
  1001: ['Protection (Pokrov) of the Most-Holy Theotokos'], // 10-01
  1002: [
    'Hieromartyr Cyprian, Martyrs Justina and Theoctistus',
    'Bl. Andrew, Fool-for-Christ'
  ], // 10-02
  1003: ['Hieromartyr Dionysius the Areopagite'], // 10-03
  1004: [
    'Hieromartyr Hierotheus, Bishop of Athens',
    'Unc. Rel. Gurias of Kazan and Varsanuphy of Tver'
  ], // 10-04
  1005: ['Ss Peter, Aleksy, Jonah, Philip, Germogen, Metrs. Moscow'], // 10-05
  1006: ['St Innocent, Metr. of Moscow / Holy Apostle Thomas'], // 10-06
  1007: ['Martyrs Sergius and Bacchus in Syria'], // 10-07
  1008: ['Ven. Pelagia the Penitent'], // 10-08
  1009: [
    'St Tikhon, Patriarch of Moscow / Holy Apostle James, Son of Alphaeus'
  ], // 10-09
  1010: ['Martyrs Eulampius and Eulampia at Nicomedia'], // 10-10
  1011: ['Apostle Philip of the Seventy'], // 10-11
  1012: ['Martyrs Probus, Tarachus and Andronicus'], // 10-12
  1013: ['Martyr Carpus and Companions at Pergamus'], // 10-13
  1014: ['Ven. Parasceva of Serbia'], // 10-14
  1015: ['Ven. Euthymius the New of Thessalonica'], // 10-15
  1016: ['Martyr Longinus the Centurion'], // 10-16
  1017: ['Prophet Hosea'], // 10-17
  1018: ['Holy Apostle and Evangelist Luke'], // 10-18
  1019: ['Prophet Joel', 'Relics Ven. John of Rila'], // 10-19
  1020: ['Greatmartyr Artemius at Antioch'], // 10-20
  1021: ['Ven. Hilarion the Great'], // 10-21
  1022: ['St Abercius, Equal-to-the-Apostles'], // 10-22
  1023: ['Holy Apostle James, Brother of the Lord'], // 10-23
  1024: ['Martyr Arethas and Companions'], // 10-24
  1025: ['Martyrs Marcian and Martyrius the Notaries'], // 10-25
  1026: ['Greatmartyr Demetrius'], // 10-26
  1027: ['Martyr Nestor of Thessalonica'], // 10-27
  1028: [
    'Martyrs Terence, Neonila and Children',
    'St Arsenius of Serbia'
  ], // 10-28
  1029: ['Martyr Anastasia the Roman'], // 10-29
  1030: ['Hieromartyr Zenobius and His Sister Zenobia'], // 10-30
  1031: ['Hieromartyr John Kochurov'], // 10-31
  1101: ['Unmercenaries and Wonderworkers Cosmas and Damian'], // 11-01
  1102: ['Martyr Acindynus of Persia and Others'], // 11-02
  1103: ['Martyrs Acepsimus, Joseph, Aithalas'], // 11-03
  1104: ['Ven. Joannicus the Great'], // 11-04
  1105: [
    'Martyrs Galacteon and Wife Epistemis',
    'Repose St Jonah of Novgorod'
  ], // 11-05
  1106: ['St Paul the Confessor of Constantinople'], // 11-06
  1107: ['Holy 33 Martyrs of Melitene'], // 11-07
  1108: ['Synaxis of Archangel Michael and the Bodiless Powers'], // 11-08
  1109: ['Martyrs Onesiphorus and Porphyrius'], // 11-09
  1110: [
    'Apostles of the 70 Erastus, Olympas, Herodion, Sosipater, Quartus, Tertius'
  ], // 11-10
  1111: ['Martyrs Menas, Victor and Vincent'], // 11-11
  1112: ['St John the Merciful, Patriarch of Alexandria'], // 11-12
  1113: ['St John Chrysostom, Archbishop of Constantinople'], // 11-13
  1114: ['Holy Apostle Philip'], // 11-14
  1115: ['Begin Nativity Fast'], // 11-15
  1116: ['Holy Apostle and Evangelist Mathew'], // 11-16
  1117: ['St Gregory the Wonderworker', 'Ven. Nikon of Radonezh'], // 11-17
  1118: ['Martyrs Platon and Roman'], // 11-18
  1119: ['Prophet Obadiah', 'Ven. Barlaam and Joasaph'], // 11-19
  1120: ['Ven. Gregory Decapolites'], // 11-20
  1121: ['Entry of the Most-Holy Theotokos into the Temple'], // 11-21
  1122: [
    'Apostles of the 70 Philemon, Archippus, Apphia',
    'St Michael, Prince of Tver'
  ], // 11-22
  1123: ['Rt. Blv. Great Prince Alexander Nevsky'], // 11-23
  1124: ['Greatmartyr Catherine of Alexandria'], // 11-24
  1125: ['Leavetaking of the Entry'], // 11-25
  1126: ['Ven. Alypius the Stylite'], // 11-26
  1127: ['Greatmartyr Jacob of Persia'], // 11-27
  1128: ['Monk Martyr and Confessor Stephen the New'], // 11-28
  1129: ['Martyr Paramon and Companions'], // 11-29
  1130: ['Holy Apostle Andrew the First Called'], // 11-30
  1201: ['Prophet Nahum'], // 12-01
  1202: ['Prophet Habbakuk'], // 12-02
  1203: ['Prophet Zephaniah', 'Ven. Savva of Zvenigorod'], // 12-03
  1204: ['Hieromartyr Alexander Hotovitzky'], // 12-04
  1205: ['Ven. Sabbas the Sanctified'], // 12-05
  1206: ['St Nicholas the Wonderworker, Abp. of Myra in Lycia'], // 12-06
  1207: ['St Ambrose, Bishop of Milan', 'Ven. Nilus of Stolobensk'], // 12-07
  1208: ['Ven. Patapius of Thebes'], // 12-08
  1209: ['Conception by St Anna of the Theotokos'], // 12-09
  1210: ['Martyrs Menas, Hermogenes, Eugraphus'], // 12-10
  1211: ['Ven. Daniel the Stylite'], // 12-11
  1212: ['St Spyridon the Wonderworker'], // 12-12
  1213: ['Repose Ven. Herman of Alaska, Wonderworker of All America'], // 12-13
  1214: ['Martyrs Thyrsus, Leucis, Callinicus'], // 12-14
  1215: ['Hieromartyr Eleutherius of Illyria', 'St Stephen of Surozh'], // 12-15
  1216: ['Prophet Haggai'], // 12-16
  1217: ['Holy Prophet Daniel and Three Holy Youths'], // 12-17
  1218: ['Martyr Sebastian and Companions at Rome'], // 12-18
  1219: ['Martyr Boniface and Righteous Aglaida'], // 12-19
  1220: [
    'Repose of St. John of Kronstadt',
    'Forefeast of Nativity',
    'Hieromartyr Ignatius the Godbearer'
  ], // 12-20
  1221: ['Virgin Martyr Juliana and Companions'], // 12-21
  1222: ['Greatmartyr Anastasia and Companions'], // 12-22
  1223: ['Holy Ten Martyrs of Crete'], // 12-23
  1225: ['Nativity of Christ'], // 12-25
  1226: [
    'Synaxis of the Most-Holy Theotokos',
    'Hieromartyr Euthymius of Sardis'
  ], // 12-26
  1227: ['Protomartyr Stephen'], // 12-27
  1228: ['20,000 Martyrs of Nicomedia'], // 12-28
  1229: ['Holy Innocents Slain by Herod'], // 12-29
  1230: ['Virgin Martyr Anysia at Thessalonica'], // 12-30
  1231: ['Ven. Melania the Younger of Rome'], // 12-31
};

/// Moveable-cycle commemoration names, keyed by pdist.
const Map<int, List<String>> movableCommemorationNames = {
  -77: ['Sunday of Zacchaeus'],
  -70: [
    'Beginning of the Lenten Triodion',
    'Sunday of the Publican and the Pharisee'
  ],
  -63: ['Sunday of the Prodigal Son'],
  -62: ['Monday of Meatfare'],
  -61: ['Tuesday of Meatfare'],
  -60: ['Wednesday of Meatfare'],
  -59: ['Thursday of Meatfare'],
  -58: ['Friday of Meatfare'],
  -57: ['Memorial Saturday', 'Saturday of Meatfare'],
  -56: ['Sunday of the Last Judgment', 'Sunday of Meatfare'],
  -55: ['Monday of Cheesefare'],
  -54: ['Cheesefare Tuesday'],
  -53: ['Cheesefare Wednesday'],
  -52: ['Cheesefare Thursday'],
  -51: ['Cheesefare Friday'],
  -50: ['Commemoration of Departed Righteous Monastics', 'Cheesefare Saturday'],
  -49: ['Forgiveness Sunday', 'Sunday of Cheesefare'],
  -48: ['Beginning of the Great Fast', 'Monday of the First Week of Lent'],
  -47: ['Tuesday of the First Week of Lent'],
  -46: ['Wednesday of the First Week of Lent'],
  -45: ['Thursday of the First Week of Lent'],
  -44: ['Friday of the First Week of Lent'],
  -43: ['St Theodore Tyro (the Recruit)', 'First Saturday of Lent'],
  -42: ['Sunday of Orthodoxy', 'First Sunday of Lent'],
  -41: ['Monday of the Second Week of Lent'],
  -40: ['Tuesday of the Second Week of Lent'],
  -39: ['Wednesday of the Second Week of Lent'],
  -38: ['Thursday of the Second Week of Lent'],
  -37: ['Friday of the Second Week of Lent'],
  -36: ['Memorial Saturday', 'Second Saturday of Lent'],
  -35: ['St Gregory Palamas', 'Second Sunday of Lent'],
  -34: ['Monday of the Third Week of Lent'],
  -33: ['Tuesday of the Third Week of Lent'],
  -32: ['Wednesday of the Third Week of Lent'],
  -31: ['Thursday of the Third Week of Lent'],
  -30: ['Friday of the Third Week of Lent'],
  -29: ['Memorial Saturday', 'Third Saturday of Lent'],
  -28: ['Veneration of the Precious Cross', 'Third Sunday of Lent'],
  -27: ['Monday of the Fourth Week of Lent'],
  -26: ['Tuesday of the Fourth Week of Lent'],
  -25: ['Wednesday of the Fourth Week of Lent'],
  -24: ['Thursday of the Fourth Week of Lent'],
  -23: ['Friday of the Fourth Week of Lent'],
  -22: ['Memorial Saturday', 'Fourth Saturday of Lent'],
  -21: ['St John Climacus', 'Fourth Sunday of Lent'],
  -20: ['Monday of the Fifth Week of Lent'],
  -19: ['Tuesday of the Fifth Week of Lent'],
  -18: ['Wednesday of the Fifth Week of Lent'],
  -17: [
    'Great Canon of St Andrew of Crete',
    'Thursday of the Fifth Week of Lent',
    'Presanctified Liturgy'
  ],
  -16: ['Friday of the Fifth Week of Lent'],
  -15: [
    'Saturday of the Akathist to the Most-Holy Theotokos',
    'Fifth Saturday of Lent'
  ],
  -14: ['St Mary of Egypt', 'Fifth Sunday of Lent'],
  -13: ['Monday of the Sixth Week of Lent'],
  -12: ['Tuesday of the Sixth Week of Lent'],
  -11: ['Wednesday of the Sixth Week of Lent'],
  -10: ['Thursday of the Sixth Week of Lent'],
  -9: ['Friday of the Sixth Week of Lent'],
  -8: ['Lazarus Saturday'],
  -7: ['Palm Sunday'],
  -6: ['Great and Holy Monday'],
  -5: ['Great and Holy Tuesday'],
  -4: ['Great and Holy Wednesday'],
  -3: ['Great and Holy Thursday'],
  -2: ['Great and Holy Friday'],
  -1: ['Great and Holy Saturday'],
  0: [
    'The Resurrection of our Lord and Savior Jesus Christ',
    'Holy Pascha',
    'Beginning of the Pentecostarion'
  ],
  1: ['Bright Monday'],
  2: ['Bright Tuesday'],
  3: ['Bright Wednesday'],
  4: ['Bright Thursday'],
  5: ['The Life-Giving Spring of the Most-holy Theotokos', 'Bright Friday'],
  6: ['Bright Saturday'],
  7: ['St Thomas Sunday', 'Antipascha: 2nd Sunday of Pascha'],
  8: ['Monday of the 2nd Sunday of Pascha'],
  9: ['Day of Rejoicing (Radonitsa)', 'Tuesday of the 2nd Sunday of Pascha'],
  10: ['Wednesday of the 2nd Sunday of Pascha'],
  11: ['Thursday of the 2nd Sunday of Pascha'],
  12: ['Friday of the 2nd Sunday of Pascha'],
  13: ['Saturday of the 2nd Sunday of Pascha'],
  14: ['Myrrhbearing Women', '3rd Sunday of Pascha'],
  15: ['Monday of the 3rd Sunday of Pascha'],
  16: ['Tuesday of the 3rd Sunday of Pascha'],
  17: ['Wednesday of the 3rd Sunday of Pascha'],
  18: ['Thursday of the 3rd Sunday of Pascha'],
  19: ['Friday of the 3rd Sunday of Pascha'],
  20: ['Saturday of the 3rd Sunday of Pascha'],
  21: ['Paralytic', '4th Sunday of Pascha'],
  22: ['Monday of the 4th Sunday of Pascha'],
  23: ['Tuesday of the 4th Sunday of Pascha'],
  24: ['Midfeast of Pentecost', 'Wednesday of the 4th Sunday of Pascha'],
  25: ['Thursday of the 4th Sunday of Pascha'],
  26: ['Friday of the 4th Sunday of Pascha'],
  27: ['Saturday of the 4th Sunday of Pascha'],
  28: ['Samaritan Woman', '5th Sunday of Pascha'],
  29: ['Monday of the 5th Sunday of Pascha'],
  30: ['Tuesday of the 5th Sunday of Pascha'],
  31: ['Leavetaking of Mid-Pentecost', 'Wednesday of the 5th Sunday of Pascha'],
  32: ['Thursday of the 5th Sunday of Pascha'],
  33: ['Friday of the 5th Sunday of Pascha'],
  34: ['Saturday of the 5th Sunday of Pascha'],
  35: ['Blind Man', '6th Sunday of Pascha'],
  36: ['Monday of the 6th Sunday of Pascha'],
  37: ['Tuesday of the 6th Sunday of Pascha'],
  38: [
    'Leavetaking of Pascha / Forefeast of Ascension',
    'Wednesday of the 6th Sunday of Pascha'
  ],
  39: [
    'Ascension of the Lord',
    'The Ascension of our Lord, God, and Saviour Jesus Christ'
  ],
  40: ['Friday of the 6th Sunday of Pascha'],
  41: ['Saturday of the 6th Sunday of Pascha'],
  42: ['Holy Fathers of the First Ecumenical Council', '7th Sunday of Pascha'],
  43: ['Monday of the 7th Sunday of Pascha'],
  44: ['Tuesday of the 7th Sunday of Pascha'],
  45: ['Wednesday of the 7th Sunday of Pascha'],
  46: ['Thursday of the 7th Sunday of Pascha'],
  47: ['Leavetaking of Ascension', 'Friday of the 7th Sunday of Pascha'],
  48: ['Memorial Saturday', 'Saturday of the 7th Sunday of Pascha'],
  49: ['Holy Pentecost', '8th Sunday of Pascha'],
  50: ['Day of the Holy Spirit', 'Monday of the 1st week after Pentecost'],
  51: ['Third Day of the Trinity', 'Tuesday of the 1st week after Pentecost'],
  52: ['Wednesday of the 1st week after Pentecost'],
  53: ['Thursday of the 1st week after Pentecost'],
  54: ['Friday of the 1st week after Pentecost'],
  55: ['Leavetaking of Pentecost', 'Saturday of the 1st week after Pentecost'],
  56: ['All Saints', '1st Sunday after Pentecost'],
  57: ['Monday of the 2nd week after Pentecost'],
  58: ['Tuesday of the 2nd week after Pentecost'],
  59: ['Wednesday of the 2nd week after Pentecost'],
  60: ['Thursday of the 2nd week after Pentecost'],
  61: ['Friday of the 2nd week after Pentecost'],
  62: ['Saturday of the 2nd week after Pentecost'],
  63: [
    'All Saints of America, All Saints of Russia',
    '2nd Sunday after Pentecost'
  ],
  64: ['Monday of the 3rd week after Pentecost'],
  65: ['Tuesday of the 3rd week after Pentecost'],
  66: ['Wednesday of the 3rd week after Pentecost'],
  67: ['Thursday of the 3rd week after Pentecost'],
  68: ['Friday of the 3rd week after Pentecost'],
  69: ['Saturday of the 3rd week after Pentecost'],
  70: ['3rd Sunday after Pentecost'],
  71: ['Monday of the 4th week after Pentecost'],
  72: ['Tuesday of the 4th week after Pentecost'],
  73: ['Wednesday of the 4th week after Pentecost'],
  74: ['Thursday of the 4th week after Pentecost'],
  75: ['Friday of the 4th week after Pentecost'],
  76: ['Saturday of the 4th week after Pentecost'],
  77: ['4th Sunday after Pentecost'],
  78: ['Monday of the 5th week after Pentecost'],
  79: ['Tuesday of the 5th week after Pentecost'],
  80: ['Wednesday of the 5th week after Pentecost'],
  81: ['Thursday of the 5th week after Pentecost'],
  82: ['Friday of the 5th week after Pentecost'],
  83: ['Saturday of the 5th week after Pentecost'],
  84: ['5th Sunday after Pentecost'],
  85: ['Monday of the 6th week after Pentecost'],
  86: ['Tuesday of the 6th week after Pentecost'],
  87: ['Wednesday of the 6th week after Pentecost'],
  88: ['Thursday of the 6th week after Pentecost'],
  89: ['Friday of the 6th week after Pentecost'],
  90: ['Saturday of the 6th week after Pentecost'],
  91: ['6th Sunday after Pentecost'],
  92: ['Monday of the 7th week after Pentecost'],
  93: ['Tuesday of the 7th week after Pentecost'],
  94: ['Wednesday of the 7th week after Pentecost'],
  95: ['Thursday of the 7th week after Pentecost'],
  96: ['Friday of the 7th week after Pentecost'],
  97: ['Saturday of the 7th week after Pentecost'],
  98: ['7th Sunday after Pentecost'],
  99: ['Monday of the 8th week after Pentecost'],
  100: ['Tuesday of the 8th week after Pentecost'],
  101: ['Wednesday of the 8th week after Pentecost'],
  102: ['Thursday of the 8th week after Pentecost'],
  103: ['Friday of the 8th week after Pentecost'],
  104: ['Saturday of the 8th week after Pentecost'],
  105: ['8th Sunday after Pentecost'],
  106: ['Monday of the 9th week after Pentecost'],
  107: ['Tuesday of the 9th week after Pentecost'],
  108: ['Wednesday of the 9th week after Pentecost'],
  109: ['Thursday of the 9th week after Pentecost'],
  110: ['Friday of the 9th week after Pentecost'],
  111: ['Saturday of the 9th week after Pentecost'],
  112: ['9th Sunday after Pentecost'],
  113: ['Monday of the 10th week after Pentecost'],
  114: ['Tuesday of the 10th week after Pentecost'],
  115: ['Wednesday of the 10th week after Pentecost'],
  116: ['Thursday of the 10th week after Pentecost'],
  117: ['Friday of the 10th week after Pentecost'],
  118: ['Saturday of the 10th week after Pentecost'],
  119: ['10th Sunday after Pentecost'],
  120: ['Monday of the 11th week after Pentecost'],
  121: ['Tuesday of the 11th week after Pentecost'],
  122: ['Wednesday of the 11th week after Pentecost'],
  123: ['Thursday of the 11th week after Pentecost'],
  124: ['Friday of the 11th week after Pentecost'],
  125: ['Saturday of the 11th week after Pentecost'],
  126: ['11th Sunday after Pentecost'],
  127: ['Monday of the 12th week after Pentecost'],
  128: ['Tuesday of the 12th week after Pentecost'],
  129: ['Wednesday of the 12th week after Pentecost'],
  130: ['Thursday of the 12th week after Pentecost'],
  131: ['Friday of the 12th week after Pentecost'],
  132: ['Saturday of the 12th week after Pentecost'],
  133: ['12th Sunday after Pentecost'],
  134: ['Monday of the 13th week after Pentecost'],
  135: ['Tuesday of the 13th week after Pentecost'],
  136: ['Wednesday of the 13th week after Pentecost'],
  137: ['Thursday of the 13th week after Pentecost'],
  138: ['Friday of the 13th week after Pentecost'],
  139: ['Saturday of the 13th week after Pentecost'],
  140: ['13th Sunday after Pentecost'],
  141: ['Monday of the 14th week after Pentecost'],
  142: ['Tuesday of the 14th week after Pentecost'],
  143: ['Wednesday of the 14th week after Pentecost'],
  144: ['Thursday of the 14th week after Pentecost'],
  145: ['Friday of the 14th week after Pentecost'],
  146: ['Saturday of the 14th week after Pentecost'],
  147: ['14th Sunday after Pentecost'],
  148: ['Monday of the 15th week after Pentecost'],
  149: ['Tuesday of the 15th week after Pentecost'],
  150: ['Wednesday of the 15th week after Pentecost'],
  151: ['Thursday of the 15th week after Pentecost'],
  152: ['Friday of the 15th week after Pentecost'],
  153: ['Saturday of the 15th week after Pentecost'],
  154: ['15th Sunday after Pentecost'],
  155: ['Monday of the 16th week after Pentecost'],
  156: ['Tuesday of the 16th week after Pentecost'],
  157: ['Wednesday of the 16th week after Pentecost'],
  158: ['Thursday of the 16th week after Pentecost'],
  159: ['Friday of the 16th week after Pentecost'],
  160: ['Saturday of the 16th week after Pentecost'],
  161: ['16th Sunday after Pentecost'],
  162: ['Monday of the 17th week after Pentecost'],
  163: ['Tuesday of the 17th week after Pentecost'],
  164: ['Wednesday of the 17th week after Pentecost'],
  165: ['Thursday of the 17th week after Pentecost'],
  166: ['Friday of the 17th week after Pentecost'],
  167: ['Saturday of the 17th week after Pentecost'],
  168: ['17th Sunday after Pentecost'],
  169: ['Monday of the 18th week after Pentecost'],
  170: ['Tuesday of the 18th week after Pentecost'],
  171: ['Wednesday of the 18th week after Pentecost'],
  172: ['Thursday of the 18th week after Pentecost'],
  173: ['Friday of the 18th week after Pentecost'],
  174: ['Saturday of the 18th week after Pentecost'],
  175: ['18th Sunday after Pentecost'],
  176: ['Monday of the 19th week after Pentecost'],
  177: ['Tuesday of the 19th week after Pentecost'],
  178: ['Wednesday of the 19th week after Pentecost'],
  179: ['Thursday of the 19th week after Pentecost'],
  180: ['Friday of the 19th week after Pentecost'],
  181: ['Saturday of the 19th week after Pentecost'],
  182: ['19th Sunday after Pentecost'],
  183: ['Monday of the 20th week after Pentecost'],
  184: ['Tuesday of the 20th week after Pentecost'],
  185: ['Wednesday of the 20th week after Pentecost'],
  186: ['Thursday of the 20th week after Pentecost'],
  187: ['Friday of the 20th week after Pentecost'],
  188: ['Saturday of the 20th week after Pentecost'],
  189: ['20th Sunday after Pentecost'],
  190: ['Monday of the 21st week after Pentecost'],
  191: ['Tuesday of the 21st week after Pentecost'],
  192: ['Wednesday of the 21st week after Pentecost'],
  193: ['Thursday of the 21st week after Pentecost'],
  194: ['Friday of the 21st week after Pentecost'],
  195: ['Saturday of the 21st week after Pentecost'],
  196: ['21st Sunday after Pentecost'],
  197: ['Monday of the 22nd week after Pentecost'],
  198: ['Tuesday of the 22nd week after Pentecost'],
  199: ['Wednesday of the 22nd week after Pentecost'],
  200: ['Thursday of the 22nd week after Pentecost'],
  201: ['Friday of the 22nd week after Pentecost'],
  202: ['Saturday of the 22nd week after Pentecost'],
  203: ['22nd Sunday after Pentecost'],
  204: ['Monday of the 23rd week after Pentecost'],
  205: ['Tuesday of the 23rd week after Pentecost'],
  206: ['Wednesday of the 23rd week after Pentecost'],
  207: ['Thursday of the 23rd week after Pentecost'],
  208: ['Friday of the 23rd week after Pentecost'],
  209: ['Saturday of the 23rd week after Pentecost'],
  210: ['23rd Sunday after Pentecost'],
  211: ['Monday of the 24th week after Pentecost'],
  212: ['Tuesday of the 24th week after Pentecost'],
  213: ['Wednesday of the 24th week after Pentecost'],
  214: ['Thursday of the 24th week after Pentecost'],
  215: ['Friday of the 24th week after Pentecost'],
  216: ['Saturday of the 24th week after Pentecost'],
  217: ['24th Sunday after Pentecost'],
  218: ['Monday of the 25th week after Pentecost'],
  219: ['Tuesday of the 25th week after Pentecost'],
  220: ['Wednesday of the 25th week after Pentecost'],
  221: ['Thursday of the 25th week after Pentecost'],
  222: ['Friday of the 25th week after Pentecost'],
  223: ['Saturday of the 25th week after Pentecost'],
  224: ['25th Sunday after Pentecost'],
  225: ['Monday of the 26th week after Pentecost'],
  226: ['Tuesday of the 26th week after Pentecost'],
  227: ['Wednesday of the 26th week after Pentecost'],
  228: ['Thursday of the 26th week after Pentecost'],
  229: ['Friday of the 26th week after Pentecost'],
  230: ['Saturday of the 26th week after Pentecost'],
  231: ['26th Sunday after Pentecost'],
  232: ['Monday of the 27th week after Pentecost'],
  233: ['Tuesday of the 27th week after Pentecost'],
  234: ['Wednesday of the 27th week after Pentecost'],
  235: ['Thursday of the 27th week after Pentecost'],
  236: ['Friday of the 27th week after Pentecost'],
  237: ['Saturday of the 27th week after Pentecost'],
  238: ['27th Sunday after Pentecost'],
  239: ['Monday of the 28th week after Pentecost'],
  240: ['Tuesday of the 28th week after Pentecost'],
  241: ['Wednesday of the 28th week after Pentecost'],
  242: ['Thursday of the 28th week after Pentecost'],
  243: ['Friday of the 28th week after Pentecost'],
  244: ['Saturday of the 28th week after Pentecost'],
  245: ['28th Sunday after Pentecost'],
  246: ['Monday of the 29th week after Pentecost'],
  247: ['Tuesday of the 29th week after Pentecost'],
  248: ['Wednesday of the 29th week after Pentecost'],
  249: ['Thursday of the 29th week after Pentecost'],
  250: ['Friday of the 29th week after Pentecost'],
  251: ['Saturday of the 29th week after Pentecost'],
  252: ['29th Sunday after Pentecost'],
  253: ['Monday of the 30th week after Pentecost'],
  254: ['Tuesday of the 30th week after Pentecost'],
  255: ['Wednesday of the 30th week after Pentecost'],
  256: ['Thursday of the 30th week after Pentecost'],
  257: ['Friday of the 30th week after Pentecost'],
  258: ['Saturday of the 30th week after Pentecost'],
  259: ['30th Sunday after Pentecost'],
  260: ['Monday of the 31st week after Pentecost'],
  261: ['Tuesday of the 31st week after Pentecost'],
  262: ['Wednesday of the 31st week after Pentecost'],
  263: ['Thursday of the 31st week after Pentecost'],
  264: ['Friday of the 31st week after Pentecost'],
  265: ['Saturday of the 31st week after Pentecost'],
  266: ['31st Sunday after Pentecost'],
  267: ['Monday of the 32nd week after Pentecost'],
  268: ['Tuesday of the 32nd week after Pentecost'],
  269: ['Wednesday of the 32nd week after Pentecost'],
  270: ['Thursday of the 32nd week after Pentecost'],
  271: ['Friday of the 32nd week after Pentecost'],
  272: ['Saturday of the 32nd week after Pentecost'],
  273: ['32nd Sunday after Pentecost'],
  274: ['Monday of the 33rd week after Pentecost'],
  275: ['Tuesday of the 33rd week after Pentecost'],
  276: ['Wednesday of the 33rd week after Pentecost'],
  277: ['Thursday of the 33rd week after Pentecost'],
  278: ['Friday of the 33rd week after Pentecost'],
  279: ['Saturday of the 33rd week after Pentecost'],
  280: ['33rd Sunday after Pentecost'],
  281: ['Monday of the 34th week after Pentecost'],
  282: ['Tuesday of the 34th week after Pentecost'],
  283: ['Wednesday of the 34th week after Pentecost'],
  284: ['Thursday of the 34th week after Pentecost'],
  285: ['Friday of the 34th week after Pentecost'],
  286: ['Saturday of the 34th week after Pentecost'],
  287: ['34th Sunday after Pentecost'],
  288: ['Monday of the 35th week after Pentecost'],
  289: ['Tuesday of the 35th week after Pentecost'],
  290: ['Wednesday of the 35th week after Pentecost'],
  291: ['Thursday of the 35th week after Pentecost'],
  292: ['Friday of the 35th week after Pentecost'],
  293: ['Saturday of the 35th week after Pentecost'],
  294: ['35th Sunday after Pentecost'],
  295: ['Monday of the 36th week after Pentecost'],
  296: ['Tuesday of the 36th week after Pentecost'],
  297: ['Wednesday of the 36th week after Pentecost'],
  298: ['Thursday of the 36th week after Pentecost'],
  299: ['Friday of the 36th week after Pentecost'],
  300: ['Saturday of the 36th week after Pentecost'],
  301: ['36th Sunday after Pentecost'],
  302: ['Monday of the 37th week after Pentecost'],
  303: ['Tuesday of the 37th week after Pentecost'],
  304: ['Wednesday of the 37th week after Pentecost'],
  305: ['Thursday of the 37th week after Pentecost'],
  306: ['Friday of the 37th week after Pentecost'],
  307: ['Saturday of the 37th week after Pentecost'],
  308: ['37th Sunday after Pentecost'],
  309: ['Monday of the 38th week after Pentecost'],
  310: ['Tuesday of the 38th week after Pentecost'],
  311: ['Wednesday of the 38th week after Pentecost'],
  312: ['Thursday of the 38th week after Pentecost'],
  313: ['Friday of the 38th week after Pentecost'],
  314: ['Saturday of the 38th week after Pentecost'],
  315: ['38th Sunday after Pentecost'],
  316: ['Monday of the 39th week after Pentecost'],
  317: ['Tuesday of the 39th week after Pentecost'],
  318: ['Wednesday of the 39th week after Pentecost'],
  319: ['Thursday of the 39th week after Pentecost'],
  320: ['Friday of the 39th week after Pentecost'],
  321: ['Saturday of the 39th week after Pentecost'],
  322: ['39th Sunday after Pentecost'],
  323: ['Monday of the 40th week after Pentecost'],
  324: ['Tuesday of the 40th week after Pentecost'],
  325: ['Wednesday of the 40th week after Pentecost'],
  326: ['Thursday of the 40th week after Pentecost'],
  327: ['Friday of the 40th week after Pentecost'],
  328: ['Saturday of the 40th week after Pentecost'],
  329: ['40th Sunday after Pentecost'],
  330: ['Monday of the 41st week after Pentecost'],
  331: ['Tuesday of the 41st week after Pentecost'],
  332: ['Wednesday of the 41st week after Pentecost'],
  333: ['Thursday of the 41st week after Pentecost'],
  334: ['Friday of the 41st week after Pentecost'],
  335: ['Saturday of the 41st week after Pentecost'],
  336: ['41st Sunday after Pentecost'],
  337: ['Monday of the 42nd week after Pentecost'],
  338: ['Tuesday of the 42nd week after Pentecost'],
  339: ['Wednesday of the 42nd week after Pentecost'],
  340: ['Thursday of the 42nd week after Pentecost'],
  341: ['Friday of the 42nd week after Pentecost'],
  342: ['Saturday of the 42nd week after Pentecost'],
  343: ['42nd Sunday after Pentecost'],
  344: ['Monday of the 43rd week after Pentecost'],
  345: ['Tuesday of the 43rd week after Pentecost'],
  346: ['Wednesday of the 43rd week after Pentecost'],
  347: ['Thursday of the 43rd week after Pentecost'],
  348: ['Friday of the 43rd week after Pentecost'],
  349: ['Saturday of the 43rd week after Pentecost'],
  350: ['43rd Sunday after Pentecost'],
  351: ['Monday of the 44th week after Pentecost'],
  352: ['Tuesday of the 44th week after Pentecost'],
  353: ['Wednesday of the 44th week after Pentecost'],
  354: ['Thursday of the 44th week after Pentecost'],
  355: ['Friday of the 44th week after Pentecost'],
  356: ['Saturday of the 44th week after Pentecost'],
  357: ['44th Sunday after Pentecost'],
};
