/// Commemoration-driven fasting exceptions, ported from the MIT-licensed
/// orthocal-python project (github.com/brianglass/orthocal-python,
/// `fixtures/calendarium.json`). Generated by tool/gen_commemorations.dart —
/// do not hand-edit; run the tool to refresh.
///
/// Values are orthocal `fast_exception` codes, combined by `max()` across the
/// day's records (higher code wins), paired with the day's `feast_level`
/// (typikon rank; polyeleos = 4+):
///   1,3,5,6,8 -> wine & oil allowed (6 = wine/oil/caviar; no fish)
///   2,4       -> fish, wine & oil allowed
///   7         -> Meat Fast (cheesefare: dairy allowed)
///   9         -> strict fast (grants nothing)
///   10        -> "no overrides": suppresses any menaion relaxation (Lenten
///                weekdays & Holy Week — 10 > every food code, so max() wins)
///   11        -> fast free
/// feast_level and fast_exception are maxed *independently*, mirroring orthocal.
///
/// FLUTTER IMPORT FORBIDDEN (architecture principle #2).
library;

/// Fixed-date (menaion) exceptions, keyed by `month * 100 + day`.
/// Value is `[fastException, feastLevel]`.
const Map<int, List<int>> fixedCommemorations = {
  101: [11, 6], // 01-01
  102: [11, 4], // 01-02
  103: [11, 0], // 01-03
  104: [11, 0], // 01-04
  105: [9, 0], // 01-05
  106: [11, 8], // 01-06
  107: [2, 3], // 01-07
  117: [2, 5], // 01-17
  120: [2, 5], // 01-20
  130: [2, 5], // 01-30
  202: [2, 8], // 02-02
  227: [2, 5], // 02-27
  324: [3, 0], // 03-24
  325: [4, 7], // 03-25
  326: [3, 3], // 03-26
  407: [1, 4], // 04-07
  423: [1, 5], // 04-23
  507: [2, 5], // 05-07
  508: [2, 5], // 05-08
  511: [2, 5], // 05-11
  624: [2, 6], // 06-24
  629: [2, 6], // 06-29
  715: [2, 5], // 07-15
  720: [2, 5], // 07-20
  801: [1, 3], // 08-01
  806: [4, 8], // 08-06
  809: [4, 5], // 08-09
  813: [4, 4], // 08-13
  815: [2, 7], // 08-15
  816: [1, 5], // 08-16
  828: [1, 4], // 08-28
  829: [8, 6], // 08-29
  901: [1, 4], // 09-01
  908: [2, 7], // 09-08
  912: [1, 0], // 09-12
  913: [1, 3], // 09-13
  914: [8, 8], // 09-14
  923: [1, 3], // 09-23
  924: [2, 4], // 09-24
  925: [2, 4], // 09-25
  926: [2, 5], // 09-26
  928: [1, 4], // 09-28
  1001: [2, 6], // 10-01
  1006: [2, 5], // 10-06
  1009: [2, 5], // 10-09
  1026: [2, 4], // 10-26
  1108: [2, 5], // 11-08
  1113: [2, 5], // 11-13
  1114: [1, 4], // 11-14
  1116: [2, 6], // 11-16
  1121: [2, 7], // 11-21
  1125: [1, 0], // 11-25
  1130: [2, 4], // 11-30
  1206: [2, 5], // 12-06
  1213: [2, 5], // 12-13
  1224: [9, 0], // 12-24
  1225: [11, 8], // 12-25
  1226: [11, 3], // 12-26
  1227: [11, 2], // 12-27
  1228: [11, 0], // 12-28
  1229: [11, 0], // 12-29
  1230: [11, 0], // 12-30
  1231: [11, 0], // 12-31
};

/// Moveable-cycle (paschal) exceptions, keyed by pdist (days from Pascha).
/// Value is `[fastException, feastLevel]`.
const Map<int, List<int>> movableCommemorations = {
  -70: [11, 0],
  -69: [11, 0],
  -68: [11, 0],
  -67: [11, 0],
  -66: [11, 0],
  -65: [11, 0],
  -64: [11, 0],
  -55: [7, 0],
  -54: [7, 0],
  -53: [7, -1],
  -52: [7, 0],
  -51: [7, -1],
  -50: [7, 0],
  -49: [7, 0],
  -48: [10, -1],
  -47: [10, -1],
  -46: [10, 1],
  -45: [10, -1],
  -44: [10, 1],
  -43: [3, 0],
  -42: [3, 0],
  -36: [3, 0],
  -35: [3, 0],
  -29: [3, 0],
  -28: [3, 0],
  -22: [3, 0],
  -21: [3, 0],
  -18: [3, 1],
  -17: [3, 0],
  -16: [3, 1],
  -15: [3, 0],
  -14: [3, 0],
  -8: [6, 0],
  -7: [4, 8],
  -6: [10, 1],
  -5: [10, 1],
  -4: [10, 1],
  -3: [3, 3],
  -2: [9, -1],
  -1: [5, 3],
  0: [11, 8],
  1: [11, 0],
  2: [11, 0],
  3: [11, 0],
  4: [11, 0],
  5: [11, 0],
  6: [11, 0],
  10: [1, 0],
  12: [1, 0],
  17: [1, 0],
  19: [1, 0],
  24: [2, 0],
  26: [1, 0],
  31: [1, 0],
  33: [1, 0],
  38: [2, 0],
  40: [1, 0],
  45: [1, 0],
  47: [1, 0],
  50: [11, 0],
  51: [11, 0],
  52: [11, 0],
  53: [11, 0],
  54: [11, 0],
  55: [11, 0],
};
