/// Dev-only tool: regenerate `lib/data/commemorations.dart` from the
/// MIT-licensed orthocal-python fasting fixture. NEVER imported by the app.
///
/// Usage:
///   dart run tool/gen_commemorations.dart
///
/// Downloads `fixtures/calendarium.json` from orthocal-python and distills it to
/// the two fast-exception lookup tables the engine needs. orthocal maxes
/// `fast_exception` and `feast_level` *independently* across each day's records,
/// so we do the same. Only days with a non-zero `fast_exception` are emitted.
library;

import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart' as http;

const _fixtureUrl =
    'https://raw.githubusercontent.com/brianglass/orthocal-python/main/fixtures/calendarium.json';

Future<void> main() async {
  stdout.writeln('Fetching $_fixtureUrl ...');
  final resp = await http.get(Uri.parse(_fixtureUrl));
  if (resp.statusCode != 200) {
    stderr.writeln('HTTP ${resp.statusCode}');
    exitCode = 1;
    return;
  }
  final list = jsonDecode(resp.body) as List<dynamic>;

  final fixed = <int, List<int>>{}; // month*100+day -> [maxFe, maxFeastLevel]
  final movable = <int, List<int>>{}; // pdist -> [maxFe, maxFeastLevel]

  // Commemoration display names, gathered separately (content data, EN-only).
  // key -> list of (name, feastLevel, fieldRank): feast_name outranks title
  // outranks individual saints; higher feast_level and lower rank sort first.
  final fixedNames = <int, List<_Named>>{};
  final movableNames = <int, List<_Named>>{};

  void bump(Map<int, List<int>> m, int key, int fe, int fl) {
    final cur = m[key];
    if (cur == null) {
      m[key] = [fe, fl];
    } else {
      if (fe > cur[0]) cur[0] = fe;
      if (fl > cur[1]) cur[1] = fl;
    }
  }

  void addNames(
      Map<int, List<_Named>> m, int key, Map<dynamic, dynamic> f, int fl) {
    final bucket = m.putIfAbsent(key, () => []);
    void add(String? raw, int rank) {
      final s = (raw ?? '').trim();
      if (s.isEmpty || s == 'null') return;
      if (bucket.any((n) => n.name == s)) return;
      bucket.add(_Named(s, fl, rank));
    }

    add(f['feast_name'] as String?, 0);
    add(f['title'] as String?, 1);
    for (final saint in (f['saint'] as String? ?? '').split(';')) {
      add(saint, 2);
    }
  }

  for (final rec in list) {
    if ((rec as Map)['model'] != 'calendarium.day') continue;
    final f = rec['fields'] as Map;
    final month = (f['month'] ?? 0) as int;
    final day = (f['day'] ?? 0) as int;
    final pdist = f['pdist'];
    final fe = (f['fast_exception'] ?? 0) as int;
    final fl = (f['feast_level'] ?? 0) as int;

    if (month > 0) {
      bump(fixed, month * 100 + day, fe, fl);
      addNames(fixedNames, month * 100 + day, f, fl);
    } else if (pdist is int && pdist < 1000) {
      bump(movable, pdist, fe, fl);
      addNames(movableNames, pdist, f, fl);
    }
  }

  fixed.removeWhere((k, v) => v[0] == 0);
  movable.removeWhere((k, v) => v[0] == 0);

  final sb = StringBuffer();
  sb.writeln('''
/// Commemoration-driven fasting exceptions, ported from the MIT-licensed
/// orthocal-python project (github.com/brianglass/orthocal-python,
/// `fixtures/calendarium.json`). Generated by tool/gen_commemorations.dart —
/// do not hand-edit; run the tool to refresh.
///
/// Values are orthocal `fast_exception` codes, combined by `max()` across the
/// day's records (higher code wins), paired with the day's `feast_level`
/// (typikon rank; polyeleos = 4+):
///   1,3,5,6,8 -> wine & oil allowed (6 = wine/oil/caviar; no fish)
///   2,4       -> fish, wine & oil allowed
///   7         -> Meat Fast (cheesefare: dairy allowed)
///   9         -> strict fast (grants nothing)
///   10        -> "no overrides": suppresses any menaion relaxation (Lenten
///                weekdays & Holy Week — 10 > every food code, so max() wins)
///   11        -> fast free
/// feast_level and fast_exception are maxed *independently*, mirroring orthocal.
///
/// FLUTTER IMPORT FORBIDDEN (architecture principle #2).
library;

/// Fixed-date (menaion) exceptions, keyed by `month * 100 + day`.
/// Value is `[fastException, feastLevel]`.
const Map<int, List<int>> fixedCommemorations = {''');
  final fk = fixed.keys.toList()..sort();
  for (final k in fk) {
    final v = fixed[k]!;
    final mm = (k ~/ 100).toString().padLeft(2, '0');
    final dd = (k % 100).toString().padLeft(2, '0');
    sb.writeln('  $k: [${v[0]}, ${v[1]}], // $mm-$dd');
  }
  sb.writeln('};');
  sb.writeln();
  sb.writeln(
      '''/// Moveable-cycle (paschal) exceptions, keyed by pdist (days from Pascha).
/// Value is `[fastException, feastLevel]`.
const Map<int, List<int>> movableCommemorations = {''');
  final mk = movable.keys.toList()..sort();
  for (final k in mk) {
    final v = movable[k]!;
    sb.writeln('  $k: [${v[0]}, ${v[1]}],');
  }
  sb.writeln('};');

  File('lib/data/commemorations.dart').writeAsStringSync(sb.toString());
  stdout.writeln('Wrote lib/data/commemorations.dart: '
      '${fixed.length} fixed, ${movable.length} movable entries.');

  // ---- commemoration_names.dart ----
  String esc(String s) => s.replaceAll(r'$', r'\$').replaceAll("'", r"\'");
  List<String> topNames(List<_Named> ns, {int cap = 4}) {
    final sorted = [...ns]..sort((a, b) {
        if (a.rank != b.rank) return a.rank - b.rank;
        return b.feastLevel - a.feastLevel;
      });
    return sorted.take(cap).map((n) => n.name).toList();
  }

  final nb = StringBuffer();
  nb.writeln('''
/// Commemoration display names (saints & feasts), ported from the MIT-licensed
/// orthocal-python fixture (`fixtures/calendarium.json`). Generated by
/// tool/gen_commemorations.dart — do not hand-edit.
///
/// Content data, English only for v1 (names are facts, no copyright — see
/// CLAUDE.md). Names per day are ordered principal-feast first. The engine's
/// titleKey still names the season/movable feast; these add the saints.
///
/// FLUTTER IMPORT FORBIDDEN (architecture principle #2).
library;

/// Fixed-date (menaion) commemoration names, keyed by `month * 100 + day`.
const Map<int, List<String>> fixedCommemorationNames = {''');
  final nfk = fixedNames.keys.toList()..sort();
  for (final k in nfk) {
    final names = topNames(fixedNames[k]!);
    if (names.isEmpty) continue;
    final mm = (k ~/ 100).toString().padLeft(2, '0');
    final dd = (k % 100).toString().padLeft(2, '0');
    final items = names.map((n) => "'${esc(n)}'").join(', ');
    nb.writeln('  $k: [$items], // $mm-$dd');
  }
  nb.writeln('};');
  nb.writeln();
  nb.writeln('/// Moveable-cycle commemoration names, keyed by pdist.');
  nb.writeln('const Map<int, List<String>> movableCommemorationNames = {');
  final nmk = movableNames.keys.toList()..sort();
  for (final k in nmk) {
    final names = topNames(movableNames[k]!);
    if (names.isEmpty) continue;
    final items = names.map((n) => "'${esc(n)}'").join(', ');
    nb.writeln('  $k: [$items],');
  }
  nb.writeln('};');

  File('lib/data/commemoration_names.dart').writeAsStringSync(nb.toString());
  stdout.writeln('Wrote lib/data/commemoration_names.dart: '
      '${fixedNames.length} fixed, ${movableNames.length} movable keys.');
}

/// A single commemoration name with its typikon rank and field precedence.
class _Named {
  const _Named(this.name, this.feastLevel, this.rank);
  final String name;
  final int feastLevel;
  final int rank; // 0 feast_name, 1 title, 2 saint
}
